title: FSG Smart Buildings
email: team@theneverwoods.com
description: ""
baseurl: ""
url: "https://fsgsmartbuildings.com"
plugins: 
  - jekyll-minifier
sass:
  style: compressed
include: 
  - _contentful
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
contentful:
  spaces:
    - content:
        space: ENV_SMART_BUILDINGS_CONTENTFUL_SPACE_ID
        access_token: ENV_SMART_BUILDINGS_CONTENTFUL_ACCESS_TOKEN
        all_entries: true
        individual_entry_files: true
        
